[package]
name = "ddns"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
base64ct = { version = "1.8.0", features = ["std"] }
color-eyre = "0.6.5"
reqwest = { version = "0.12.24", default-features = false, features = [
  "http2",
  "charset",
  "rustls-tls",
  "json",
] }
serde = { version = "1.0.228", features = ["derive"] }
subtle = "2.6.1"
tap = "1.0.1"
tokio = { version = "1.48.0", features = ["full"] }
