on:
  push:
    branches: [main]
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: native
    steps:
      - uses: actions/checkout@v5
      - uses: ./.forgejo/checkout-head
      - run: nix-build -A ci.check
      - run: ./result

  build:
    # Disable spinners etc
    env:
      TERM: dumb
    strategy:
      matrix:
        host: [x86_64-linux, aarch64-linux, aarch64-darwin]
    needs: check
    runs-on:
      - native
      - native-${{ matrix.host }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.forgejo/checkout-head
      - run: nix-build -A ci.build
      - name: Push to cache
        continue-on-error: true
        run: |
          nix-build -o celler-result -A pkgs.celler
          export PATH="$(readlink -f celler-result/bin):$PATH"
          celler login rab-celler 'https://celler.rab.lol' '${{ secrets.ATTIC_TOKEN }}'
          celler push rab-celler:public result
