on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: native
    steps:
      - uses: actions/checkout@v4
      - run: nix-build -A ci.check
      - run: ./result

  build:
    strategy:
      matrix:
        host: [x86_64-linux, aarch64-linux]
    needs: check
    runs-on:
      - native
      - native-${{ matrix.host }}
    steps:
      - uses: actions/checkout@v4
      - run: nix-build -A ci.build
