on:
  push:
    branches: [main]
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: native
    steps:
      - uses: actions/checkout@v5
      - uses: ./.forgejo/checkout-head
      - run: nix-build -A ci.check
      - run: ./result

  build:
    strategy:
      matrix:
        host: [x86_64-linux, aarch64-linux, aarch64-darwin]
    needs: check
    runs-on:
      - native
      - native-${{ matrix.host }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.forgejo/checkout-head
      - run: nix-build -A ci.build
      - name: Push to cache
        run: |
          nix-build -o attic-result -A pkgs.attic-client
          export PATH="$(readlink -f attic-result/bin):$PATH"
          attic login rab-attic 'https://attic.rab.lol' '${{ secrets.ATTIC_TOKEN }}'
          attic push rab-attic:public result
