name: "Attic push"
inputs:
  from:
    default: "."
  server-url:
    default: "https://attic.nrab.lol/"
  server-name:
    default: "nrab-attic"
  cache:
    default: "public"
  paths:
    default: "result"
  token:
    default: ${{ secrets.ATTIC_TOKEN }}
runs:
  using: "composite"
  steps:
    - run: |
        nix run "${{ inputs.from }}"#attic -- login "${{ inputs.server-name }}" '${{ inputs.server-url }}' '${{ inputs.token }}'
        nix run "${{ inputs.from }}"#attic -- push "${{ inputs.server-name }}":"${{ inputs.cache }}" ${{ inputs.paths }}
