name: Build flake

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-nix
      - run: nix flake check

  matrix:
    runs-on: ubuntu-latest
    outputs:
      aarch64-darwin: ${{ steps.generate_matrix.outputs.aarch64-darwin }}
      aarch64-linux: ${{ steps.generate_matrix.outputs.aarch64-linux }}
      x86_64-linux: ${{ steps.generate_matrix.outputs.x86_64-linux }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-nix
      - id: generate_matrix
        run: |
          nix eval --raw .#github-matrix >> $GITHUB_OUTPUT

  build-x86_64-linux:
    runs-on: ubuntu-latest
    needs: [matrix]
    if: ${{ needs.matrix.outputs.x86_64-linux != '[]' && needs.matrix.outputs.x86_64-linux != '' }}
    strategy:
      fail-fast: false
      matrix:
        output: ${{ fromJson(needs.matrix.outputs.x86_64-linux )}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-nix
      - name: Build output
        run: nix build .#${{ matrix.output }} -L
